### PR TITLE
fix: Concurrency race when running in parallel

### PR DESCRIPTION
**Pull request by xpzouying**
Use sync.Once to init flag variables.

fix: #98 #99

### CODE REVIEW

**Comment by marcosnils** [comment]
Thanks for the contribution. I see that tests are failing on CI.

**Comment by xpzouying** [comment]
The upstream branch couldn't pass the test. The error was not introduced by this PR. 

Please check the current unit tests.

Thank you.

**Comment by marcosnils** [comment]
`master` branch tests are currently green https://github.com/franela/goblin/runs/1215884598. Re-check on your side please.

**Comment by xpzouying** [comment]
@marcosnils fix it.

Please code review.

Thank you.

close #98  #99

**Comment by marcosnils** [comment]
LGTM!

**Review by marcosnils — APPROVED** [review]

**Pull request merged**
