### PR TITLE
fix async after each (was executed after the end)

### PR DESCRIPTION
**Pull request by schmurfy**
aftereach callbacks were executed before the test was done

### CODE REVIEW

**Comment by marcosnils** [comment]
hey @schmurfy can we add a test for this?

**Comment by schmurfy** [comment]
okay I will give it a try

**Comment by schmurfy** [comment]
I added tests and fixed and another issue I got bitten by without knowing: the order in which the after blocks are executed were wrong, local afters should be executed first, a simple example would be connecting to an external database in a before and closing it in an after.

**Comment by marcosnils** [comment]
Loved this. Thx for fixing it

**Pull request merged**
