### PR TITLE
Add testify support

### PR DESCRIPTION
**Pull request by criloz**
add support to https://github.com/stretchr/testify
implements Errorf function

### CODE REVIEW

**Comment by criloz** [comment]
```go
package foobar

import (
    "testing"
    . "github.com/franela/goblin"
    "github.com/stretchr/testify/assert"
)

func Test(t *testing.T) {
    g := Goblin(t)

    g.Describe("lala", func() {
        g.It("lslslslsls", func() {
            assert.Equal(g, 1, 10)
        })
    })
}
```

**Comment by marcosnils** [comment]
You're adding code that's not tested :S

**Comment by criloz** [comment]
@marcosnils can you tell where you test your `Fail` function?, I try to look  in the code but for my time schedule  I could not find the test case, the `Errorf` function is almost the same, with the adition  that allow format strings

**Comment by marcosnils** [comment]
> @marcosnils can you tell where do you test your Fail function?, I try to look in the code but for my time schedule I could not find the test case, the Errorf function is almost the same, with the adition that allow format strings

https://github.com/franela/goblin/blob/b50404691661f34b0cea76cb2704fe5c0ccec90f/goblin_test.go#L160-L182

**Comment by marcosnils** [comment]
@criloz `Fail` and `Failf` have almost the same code. Can you please extract the common parts function so we don't have duplicated code?

**Comment by criloz** [comment]
@marcosnils sure, will work on that tomorrow. also update the readme with the testify support example

**Comment by marcosnils** [comment]
Amazing!. Thx a lot!. We're almost there :D

**Comment by charleswhchan** [comment]
Is this feature complete?

**Comment by alexdreptu** [comment]
What happened to this?

**Comment by marcosnils** [comment]
@alexdreptu seems like it never got completed and got abandoned.

**Comment by artem-malko** [comment]
@marcosnils as I can see, it is completed! No duplicated code) May be it is ok to merge it?)

**Comment by artem-malko** [comment]
I've checked it locally — works perfectly!)

**Comment by schmurfy** [comment]
I created #85 and fixed the 2016 issue with this pr

**Comment by marcosnils** [comment]
Closed by #85

**Pull request closed without merging**
